IF
	!Global("ES_%BCS%_INIT","MYAREA",1)
THEN
	RESPONSE #100
		SetGlobal("ES_%BCS%_INIT","MYAREA",1)
		SetGlobal("ES_%BCS%","MYAREA",0)
END

IF
	Detected([ANYONE])
THEN
	RESPONSE #100
		IncrementGlobal("ES_%BCS%","MYAREA",1)
		Continue()
END

IF
	!Global("ES_%BCS%","MYAREA",0)
THEN
	RESPONSE #100
		Shout(%SHOUT_TRAP%)
		Continue()
END

IF
	OR(2)
		Disarmed([ANYONE])
		Entered([ANYONE])
THEN
	RESPONSE #100
		IncrementGlobal("ES_%BCS%","MYAREA",-1)
END