///////////////////////////////////////////////////////////////////////////////
// 적을 공격
///////////////////////////////////////////////////////////////////////////////

// 원거리 모드인데 원거리 무기가 무기 슬롯에 없으면 공격을 하지 않는다.
IF
	Global("ES_MODE","LOCALS",%MODE_RANGE%)
	!CanEquipRanged()
THEN
	RESPONSE #100
END

// 거리에 따라 무기 교체하며 공격
IF
	Global("ES_MODE","LOCALS",%MODE_MIXED%)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	!InParty(NearestEnemyOf(Myself))
	!Range(NearestEnemyOf(Myself),8)
	CanEquipRanged()
THEN
	RESPONSE #100
        EquipRanged()
		AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
	Global("ES_MODE","LOCALS",%MODE_MIXED%)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	!InParty(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
        SelectWeaponAbility(SLOT_WEAPON,0)
		AttackReevaluate(NearestEnemyOf(Myself),30)
END

// 주문 시전자부터 공격
IF
	!Global("ES_MODE","LOCALS",%MODE_MIXED%)
	ActionListEmpty()
	!See(NearestEnemyOfType([0.0.0.SORCERER]))
	!See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
	!See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
	!See(NearestEnemyOfType([0.0.0.BARD_ALL]))
	!See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
	!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
END

IF
	!Global("ES_MODE","LOCALS",%MODE_MIXED%)
	ActionListEmpty()
	!InParty(LastSeenBy(Myself))
	Allegiance(LastSeenBy(Myself),[ENEMY])
THEN
	RESPONSE #100
		AttackReevaluate(LastSeenBy(Myself),30)
END